[package]
name = "prj9"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]

[dependencies]
xmltree = "0.4.0"
cgmath = "0.15.0"
png = "0.9.0"
rayon = "0.8.2"
wavefront_obj = "5.1.0"
rand = "0.3.16"
